version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env  # Load environment variables
